### ISSUE TITLE
Do not return AFK players back to their original position

### ISSUE THREAD

**Issue by DmitryRendov** [LegendEffects/OpenAFK#7]
**Is your feature request related to a problem? Please describe.**
I do not want players back to their original position. Smth it's being changed and they appear in a lava lake eg)

**Describe the solution you'd like**
Just a boolean flag in the config.

**Describe alternatives you've considered**
Do not change a player position when return back.

**Additional context**
-

**Comment by LegendEffects** [comment]
If you want to teleport a player and not have them return I would recommend running a teleport command instead of using the AFKArea action.
